#############################################################################
# Makefile for building: pymecavideo_project
# Generated by qmake (2.01a) (Qt 4.4.3) on: jeu. mars 26 08:30:18 2009
# Project:  pymecavideo_project.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile pymecavideo_project.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib/qt4/mkspecs/linux-g++ -I. -I/usr/lib/qt4/include/QtCore -I/usr/lib/qt4/include/QtCore -I/usr/lib/qt4/include/QtGui -I/usr/lib/qt4/include/QtGui -I/usr/lib/qt4/include -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -L/usr/lib -pthread -lpng -lSM -lICE -pthread -pthread -lXi -lXrender -lXrandr -lfreetype -lfontconfig -lXext -lX11 -lQtCore -lz -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = __init__.py \
		cadreur.py \
		dbg.py \
		echelle.py \
		label_trajectoire.py \
		label_video.py \
		listes.py \
		point.py \
		preferences.py \
		table.py \
		vecteur.py \
		version.py \
		vitesse.py \
		zoom.py 
OBJECTS       = __init__.o \
		cadreur.o \
		dbg.o \
		echelle.o \
		label_trajectoire.o \
		label_video.o \
		listes.o \
		point.o \
		preferences.o \
		table.o \
		vecteur.o \
		version.o \
		vitesse.o \
		zoom.o
DIST          = /usr/lib/qt4/mkspecs/common/g++.conf \
		/usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/release.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		pymecavideo_project.pro
QMAKE_TARGET  = pymecavideo_project
DESTDIR       = 
TARGET        = pymecavideo_project

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_pymecavideo.h ui_preferences.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: pymecavideo_project.pro  /usr/lib/qt4/mkspecs/linux-g++/qmake.conf /usr/lib/qt4/mkspecs/common/g++.conf \
		/usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/release.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile pymecavideo_project.pro
/usr/lib/qt4/mkspecs/common/g++.conf:
/usr/lib/qt4/mkspecs/common/unix.conf:
/usr/lib/qt4/mkspecs/common/linux.conf:
/usr/lib/qt4/mkspecs/qconfig.pri:
/usr/lib/qt4/mkspecs/features/qt_functions.prf:
/usr/lib/qt4/mkspecs/features/qt_config.prf:
/usr/lib/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt4/mkspecs/features/default_pre.prf:
/usr/lib/qt4/mkspecs/features/release.prf:
/usr/lib/qt4/mkspecs/features/default_post.prf:
/usr/lib/qt4/mkspecs/features/warn_on.prf:
/usr/lib/qt4/mkspecs/features/qt.prf:
/usr/lib/qt4/mkspecs/features/unix/thread.prf:
/usr/lib/qt4/mkspecs/features/moc.prf:
/usr/lib/qt4/mkspecs/features/resources.prf:
/usr/lib/qt4/mkspecs/features/uic.prf:
/usr/lib/qt4/mkspecs/features/yacc.prf:
/usr/lib/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile pymecavideo_project.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/pymecavideo_project1.0.0 || $(MKDIR) .tmp/pymecavideo_project1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/pymecavideo_project1.0.0/ && $(COPY_FILE) --parents __init__.py cadreur.py dbg.py echelle.py label_trajectoire.py label_video.py listes.py point.py preferences.py table.py vecteur.py version.py vitesse.py zoom.py .tmp/pymecavideo_project1.0.0/ && $(COPY_FILE) --parents pymecavideo.ui preferences.ui .tmp/pymecavideo_project1.0.0/ && $(COPY_FILE) --parents lang/pymecavideo_fr_FR.ts lang/pymecavideo_en_EN.ts lang/pymecavideo_us_US.ts .tmp/pymecavideo_project1.0.0/ && (cd `dirname .tmp/pymecavideo_project1.0.0` && $(TAR) pymecavideo_project1.0.0.tar pymecavideo_project1.0.0 && $(COMPRESS) pymecavideo_project1.0.0.tar) && $(MOVE) `dirname .tmp/pymecavideo_project1.0.0`/pymecavideo_project1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/pymecavideo_project1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_pymecavideo.h ui_preferences.h
compiler_uic_clean:
	-$(DEL_FILE) ui_pymecavideo.h ui_preferences.h
ui_pymecavideo.h: pymecavideo.ui
	/usr/lib/qt4/bin/uic pymecavideo.ui -o ui_pymecavideo.h

ui_preferences.h: preferences.ui
	/usr/lib/qt4/bin/uic preferences.ui -o ui_preferences.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_uic_clean 

####### Compile

__init__.o: __init__.py 
	$(CC) -c $(CFLAGS) $(INCPATH) -o __init__.o __init__.py

cadreur.o: cadreur.py 
	$(CC) -c $(CFLAGS) $(INCPATH) -o cadreur.o cadreur.py

dbg.o: dbg.py 
	$(CC) -c $(CFLAGS) $(INCPATH) -o dbg.o dbg.py

echelle.o: echelle.py 
	$(CC) -c $(CFLAGS) $(INCPATH) -o echelle.o echelle.py

label_trajectoire.o: label_trajectoire.py 
	$(CC) -c $(CFLAGS) $(INCPATH) -o label_trajectoire.o label_trajectoire.py

label_video.o: label_video.py 
	$(CC) -c $(CFLAGS) $(INCPATH) -o label_video.o label_video.py

listes.o: listes.py 
	$(CC) -c $(CFLAGS) $(INCPATH) -o listes.o listes.py

point.o: point.py 
	$(CC) -c $(CFLAGS) $(INCPATH) -o point.o point.py

preferences.o: preferences.py 
	$(CC) -c $(CFLAGS) $(INCPATH) -o preferences.o preferences.py

table.o: table.py 
	$(CC) -c $(CFLAGS) $(INCPATH) -o table.o table.py

vecteur.o: vecteur.py 
	$(CC) -c $(CFLAGS) $(INCPATH) -o vecteur.o vecteur.py

version.o: version.py 
	$(CC) -c $(CFLAGS) $(INCPATH) -o version.o version.py

vitesse.o: vitesse.py 
	$(CC) -c $(CFLAGS) $(INCPATH) -o vitesse.o vitesse.py

zoom.o: zoom.py 
	$(CC) -c $(CFLAGS) $(INCPATH) -o zoom.o zoom.py

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

