#!/usr/bin/env python3

import os,sys

srcDir = os.path.join(os.path.dirname(__file__), "src")
if os.path.exists(srcDir):
    import src.pymecavideo
    src.pymecavideo.run()
else:
    import pymecavideo.pymecavideo
    pymecavideo.pymecavideo.run()
