'\" t
.\"     Title: PYMECAVIDEO
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: February 4, 2023
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "PYMECAVIDEO" "1" "February 4, 2023" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pymecavideo \- pedagogical program to teach mechanics
.SH "SYNOPSIS"
.HP \w'\fBpymecavideo\fR\ 'u
\fBpymecavideo\fR [{\fB\-d\fR\ |\ \fB\-\-debug=\fR}\ \fIverbosity\ (level:\ 1\ to\ 3)\fR] [\fB\fIfilename\&.{avi|mpg|\&.\&.\&.}\ |\ filename\&.mecavideo\fR\fR]
.SH "DESCRIPTION"
.PP
\fBpymecavideo\fR
is a program to track a set of moving points in a video frameset\&. The size of the image can be modified, then you track the relevant points and export a file containing the timecode and the coordinates, to be analyzed by some other standard software\&.
.SH "OPTIONS"
.PP
\fB\-d \fR\fB\fIlevel\fR\fR, \fB\-\-debug=\fR\fB\fIlevel\fR\fR
.RS 4
Déclares the level of verbosity to debug the application\&. this level is zero by default (no debug messages), and it can take values from 1 to 3\&.
.RE
.SH "ARGUMENTS"
.PP
\fB\fIfilename\&.{avi|mpg|\&.\&.\&.}\fR\fR
.RS 4
Defines some video file to begin with (optional)\&.
.RE
.PP
\fB\fIfilename\&.mecavideo\fR\fR
.RS 4
Allows one to open a full context saved in a previous session\&.
.RE
.SH "AUTHOR"
.PP
This manual page was written by Georges Khaznadar
<georgesk@debian\&.org>
for the
Debian(TM)
system (but may be used by others)\&. Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
General Public License, Version 3 any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common\-licenses/GPL\-3\&.
.SH "COPYRIGHT"
.br
Copyright \(co 2007-2023 Georges Khaznadar
.br
